version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: ems-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 5453
      MYSQL_DATABASE: ems_db
    ports:
      - "3306:3306"

  backend:
    image: ems-backend
    container_name: ems-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
